### ISSUE TITLE
Cannot render when using GitHub actions

### ISSUE THREAD

**Issue by ShirasawaSama** [co3moz/minecraft-render#9]
```
> minecraft-render client.jar icons/minecraft -w 40 -t 40 -d 13 -A

THREE.WebGLRenderer: Cannot read property 'getUniformLocation' of null
Rendering failed! TypeError: Cannot read property 'renderer' of undefined
    at Object.destroyRenderer (/home/runner/work/*/*/node_modules/minecraft-render/dist/render.js:54:14)
    at async Minecraft.cleanupRenderEnvironment (/home/runner/work/*/*/node_modules/minecraft-render/dist/minecraft.js:128:9)
```

My configuration:

```yaml
name: Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: sudo apt-get install -y build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config xvfb

      - run: npm i -g minecraft-render

      - run: wget https://some-url.com/client.jar

      - run: minecraft-render client.jar icons/minecraft -w 40 -t 40 -d 13 -A
```

**Comment by co3moz** [comment]
Install xvfb and run minecraft-render with it. 

```yaml
name: Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: sudo apt-get install -y build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config xvfb

      - run: npm i -g minecraft-render

      - run: wget https://some-url.com/client.jar

      - run: xvfb-run --auto-servernum minecraft-render client.jar icons/minecraft -w 40 -t 40 -d 13 -A
```

[Working example](https://github.com/co3moz/minecraft-render/blob/master/.github/workflows/ci.yml)
